### ISSUE TITLE
Documenter pour faciliter la contribution

### ISSUE THREAD

**Issue by guillett** [openfisca/biryani#8]
En lien avec #7.

Le fichier de configuration de la CI peut être le lien vers lequel pointe la documentation.

**Comment by maukoquiroga** [comment]
Hi @guillett,

We're prioritising #7 as the library is still widely used in OpenFisca.

Regarding documentation, what do you think about https://github.com/openfisca/openfisca-core/issues/691?

It seems to me effort could be better spent finding ways of factoring out code using the library.
